config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'welcome#index'
  get '/title_form', to: 'forms#new'
  get 'welcome/index'
  get 'welcome/contact'
  get 'welcome/donate'
  resources :forms, only: [:index, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/form.rb
class Form < ApplicationRecord
  validates :name_first_last, presence: true
  validates :address_street, presence: true
  validates :address_city, presence: true
  validates :address_state, presence: true
  validates :address_zip, presence: true
  validates :phone, presence: true
  validates :email, presence: true
  validates :vin, presence: true
  validates :make, presence: true
  validates :model, presence: true
  validates :year, presence: true
  validates :cc, presence: true
  validates :color, presence: true
  validates :purchase_date, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
  def new
    @form = Form.new
  end

  def create
    Form.create(name_first_last: form_params[:name_first_last].upcase, address_street: form_params[:address_street].upcase, address_city: form_params[:address_city].upcase, address_state: form_params[:address_state].upcase, address_zip: form_params[:address_zip], phone: form_params[:phone], email: form_params[:email].upcase, vin: form_params[:vin].upcase, make: form_params[:make].upcase, model: form_params[:model].upcase, year: form_params[:year], cc: form_params[:cc], color: form_params[:color].upcase, purchase_date: form_params[:purchase_date])
    pdftk = PdfForms.new('/app/vendor/pdftk/bin/pdftk')
    # PDFTK For AWS
    # pdftk = PdfForms.new('/usr/bin/pdftk')
    pdftk.fill_form "#{Rails.root}/public/title.pdf", 'starwars.pdf', form_name_first_last: form_params[:name_first_last].upcase, form_todays_date: (Time.now.strftime("%m/%d/%Y")), form_address_street: form_params[:address_street].upcase, form_address_city: form_params[:address_city].upcase, form_address_state: form_params[:address_state], form_address_zip: form_params[:address_zip], form_phone: form_params[:phone], form_email: form_params[:email].upcase, form_social: (form_params[:social].insert(3, '-').insert(6, '-')), form_vin: form_params[:vin].upcase, form_make: form_params[:make].upcase, form_model: form_params[:model].upcase, form_year: form_params[:year], form_cc: form_params[:cc], form_color: form_params[:color].upcase, form_purchase_date: form_params[:purchase_date], form_address_full: (form_params[:name_first_last].upcase + ', ' +  form_params[:address_street].upcase + ', ' + form_params[:address_city].upcase + ', ' + form_params[:address_state] + ' ' + form_params[:address_zip])
    File.open("#{Rails.root}/starwars.pdf", 'r') do |f|
      send_data f.read, type: "application/pdf", filename: "#{form_params[:name_first_last].gsub(' ','_') }_Title_Form.pdf"
    end
    File.delete("#{Rails.root}/starwars.pdf")
  end

private
  def form_params
    params.require(:form).permit(:name_first_last, :todays_date, :address_street, :address_city, :address_state, :address_zip, :phone, :email, :social, :vin, :make, :model, :year, :cc, :color, :purchase_date)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def contact
  end

  def donate
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/form_helper.rb
module FormHelper
  def us_states
    [
      ['Alabama', 'AL'],
      ['Alaska', 'AK'],
      ['Arizona', 'AZ'],
      ['Arkansas', 'AR'],
      ['California', 'CA'],
      ['Colorado', 'CO'],
      ['Connecticut', 'CT'],
      ['Delaware', 'DE'],
      ['District of Columbia', 'DC'],
      ['Florida', 'FL'],
      ['Georgia', 'GA'],
      ['Hawaii', 'HI'],
      ['Idaho', 'ID'],
      ['Illinois', 'IL'],
      ['Indiana', 'IN'],
      ['Iowa', 'IA'],
      ['Kansas', 'KS'],
      ['Kentucky', 'KY'],
      ['Louisiana', 'LA'],
      ['Maine', 'ME'],
      ['Maryland', 'MD'],
      ['Massachusetts', 'MA'],
      ['Michigan', 'MI'],
      ['Minnesota', 'MN'],
      ['Mississippi', 'MS'],
      ['Missouri', 'MO'],
      ['Montana', 'MT'],
      ['Nebraska', 'NE'],
      ['Nevada', 'NV'],
      ['New Hampshire', 'NH'],
      ['New Jersey', 'NJ'],
      ['New Mexico', 'NM'],
      ['New York', 'NY'],
      ['North Carolina', 'NC'],
      ['North Dakota', 'ND'],
      ['Ohio', 'OH'],
      ['Oklahoma', 'OK'],
      ['Oregon', 'OR'],
      ['Pennsylvania', 'PA'],
      ['Puerto Rico', 'PR'],
      ['Rhode Island', 'RI'],
      ['South Carolina', 'SC'],
      ['South Dakota', 'SD'],
      ['Tennessee', 'TN'],
      ['Texas', 'TX'],
      ['Utah', 'UT'],
      ['Vermont', 'VT'],
      ['Virginia', 'VA'],
      ['Washington', 'WA'],
      ['West Virginia', 'WV'],
      ['Wisconsin', 'WI'],
      ['Wyoming', 'WY']
    ]
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/forms/_form.html.haml
= render "layouts/errors", :object => @form
= form_for @form do |f|
  .form-group
    = f.label :name_first_last, 'First Last Name'
    = f.text_field :name_first_last, :required => true, :class => "form-control"
  .form-group
    = f.label :address_street, 'Street'
    = f.text_field :address_street, :required => true, :class => "form-control"
  .form-group
    = f.label :address_city, 'City'
    = f.text_field :address_city, :required => true, :class => "form-control"
  .form-group
    = f.label :address_state, 'State'
    = f.select :address_state, options_for_select(us_states), :required => true, :class => "form-control"
  .form-group
    = f.label :address_zip, 'Zip'
    = f.text_field :address_zip, minlength: 5, maxlength: 5, :required => true, :class => "form-control"
  .form-group
    = f.label :phone, 'Phone'
    = f.phone_field :phone, :required => true, :class => "form-control"
  .form-group
    = f.label :email, 'Email'
    = f.email_field :email, :required => true, type:'email', :class => "form-control"
  .form-group
    = f.label :social, 'Social Security Number'
    = f.text_field :social, minlength: 9, maxlength: 9, :required => true, :class => "form-control"
  .form-group
    = f.label :vin, 'Vin Number'
    = f.text_field :vin, minlength: 17, maxlength: 17, :required => true, :class => "form-control"
  .form-group
    = f.label :make, 'Make'
    = f.text_field :make, :required => true, :class => "form-control"
  .form-group
    = f.label :model, 'Model'
    = f.text_field :model, :required => true, :class => "form-control"
  .form-group
    = f.label :year, 'Year'
    = f.number_field :year, min: 1950, :required => true, :class => "form-control"
  .form-group
    = f.label :cc, 'CC'
    = f.number_field :cc, min: 250, :required => true, :class => "form-control"
  .form-group
    = f.label :color, 'Color'
    = f.text_field :color, :required => true, :class => "form-control"
  .form-group
    = f.label :purchase_date, 'Purchase Date (mm/dd/yyyy)'
    = f.text_field :purchase_date, :required => true, :class => "form-control"
  .center-align
    %br
    = f.button :Submit, class: 'btn btn-info btn-large'

app/views/forms/index.html.haml
#index-banner.parallax-container
  .section.no-pad-bot
    .container
      %br
      %br
      %h1.header.center.teal-text.text-lighten-2 Register Your Bike
      .row.center
        %h5.header.col.s12.light Fill out a simple form to get a street legal dirtbike or atv title.
      .row.center
        = link_to 'Get Started', create_path, class: 'btn-large waves-effect waves-light teal lighten-1', id: 'download-button'
      %br
      %br
  .parallax= image_tag 'background1.jpg', alt: 'Unsplashed background img 1'
.container
  .section
    .row
      .col.m4.s12
        .icon-block
          %h2.center.brown-text
            %i.material-icons mode_edit
          %h5.center Fill Out Form
          %p.light.center Fill out the form and a PDF will be generated and downloaded. Follow additional instructions to complete required paperwork.
      .col.m4.s12
        .icon-block
          %h2.center.brown-text
            %i.material-icons send
          %h5.center Send Forms
          %p.light.center Send out forms to address on pdf. You should get a call/email in a few days when your order is ready for payment.
      .col.m4.s12
        .icon-block
          %h2.center.brown-text
            %i.material-icons cake
          %h5.center Receive Title/Plates
          %p.light.center Receive plates 5-7 days after payment. Title will come 3-4 weeks after payment. You can then transfer the title to your state or just bike registered where in SD.
#index-banner.parallax-container.valign-wrapper
  .section.no-pad-bot
    .container
      .row.center
        %h1.header.col.s12.light Adventure is Out There
        %h4.header.col.s12.light “Oh the places you’ll go.” - ƒfar Seuss
  .parallax= image_tag 'background2.jpg', alt: 'Unsplashed background img 2'
.container
  .section
    .row
      .col.s16.center
        %h3
          %i.mdi-content-send.brown-text
        %h4 Why I Built This
        %p.left-align.light.center I like many of love riding. Every time you want to ride you have to load up your dirtbike, drive to a trail, park somewhere rediculouse, have your fun, then have to load it back up and do it all over again. Why not throw some legal lights on it and not have to deal with a ton of state inspections to be legal and insured. I completed this and it gave me hours of joy on my dirtbike. I hope the same to you. Please donate as your heart desires.
.teal.center.about
  .row
    .col.l6.s12
      %h5.white-text About Me
      %p.grey-text.text-lighten-4 I am a developer living in Portland, OR that loves to build cool tool/gadgets. I love riding, hiking, and anything outdoors. Please donate to keep this site up and to get more riders on the trails. Any amount would help support and continue development and is greatly appreciated
    .col.l6.s12.center
      %h5.white-text Donate
      %br
      = link_to 'Donate', 'https://cash.me/$DanielDanilyuk', class: 'btn-large waves-effect waves-light green lighten-1', id: 'download-button', target: '_blank'

app/views/forms/new.html.haml
.container
  %h1.center Legal Title Form
  %h3.center Fill out all fields on form.
  %h5.center (USE YOUR REALL ADDRESS. MAKE SURE INFO MATCHES DRIVERS LISCENCE. ITS OK IF ITS NOT IN SD)
  = render 'form'
  %br
  %br

app/views/layouts/_errors.html.haml
- if object.errors.any?
  %h3 Please fix these errors:
  %ul
    - object.errors.full_messages.each do |message|
      %li= message

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %title Legal Off-Road
    = favicon_link_tag 'tab_icon.png'
    = csrf_meta_tags
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}
    = stylesheet_link_tag    'application', media: 'screen'
    = javascript_include_tag 'application'
  %body
    #container
      %nav.white{:role => "navigation"}
        .nav-wrapper.container
          = link_to 'Legal Off-Road', root_path, class: 'brand-logo', id: 'logo-container'
          .hide-on-small-only
            %ul.right
              %li= link_to 'Form', title_form_path
              %li= link_to 'Donate', welcome_donate_path
              %li= link_to 'Contact', welcome_contact_path
          .hide-on-med-and-up
            %ul#slide-out.sidenav
              %li= link_to 'Home', root_path
              %li= link_to 'Form', title_form_path
              %li= link_to 'Donate', welcome_donate_path
              %li= link_to 'Contact', welcome_contact_path
            = link_to root_path, class: "button-collapse sidenav-trigger",id: "test-button", "data-target" => "slide-out" do
              %i.material-icons menu
      #body
        - flash.each do |key, value|
          .alert.alert-info.alert-dismissible.fade.show{:role => "alert"}
            %button.close{"aria-label" => "Close", "data-dismiss" => "alert", :type => "button"}
              %span{"aria-hidden" => "true"} ×
            = value
        = yield
      #footer
        .footer-copyright.center
          Made by
          %a.brown-text.text-lighten-3{:href => "http://www.dandanilyuk.com"} Dan Danilyuk

app/views/welcome/contact.html.haml
%h1 Welcome#contact
%p Find me in app/views/welcome/contact.html.haml

app/views/welcome/donate.html.haml
#index-banner.parallax-container
  .section.no-pad-bot
    .container
      %br
      %br
      %h1.header.center.teal-text.text-lighten-2 Register Your Bike
      .row.center
        %h5.header.col.s12.light Fill out a simple form to get a street legal dirtbike or atv title.
      
      %br
      %br
  .parallax= image_tag 'background3.jpg', alt: 'Unsplashed background img 1'
.container
  .section
    .row
      .col.s16.center
        %h3
          %i.mdi-content-send.brown-text
        %h4 Please Donate
        %p.left-align.light.center Please donate to keep Legal Off-Road up and running. It is a free service (others charge hundreds) and we will keep it free as long as we can. Even a small donation of 5$ is greatly appreciated.
      .row.center
        %form{action: 'https://www.paypal.com/cgi-bin/webscr', method: 'post', target: '_blank'}
          %input{name: 'cmd', type: 'hidden', value: '_donations'}
          %input{name: 'business', type: 'hidden', value: 'KVHNU3QL5C2HN'}
          %input{name: 'item_name', type: 'hidden', value: 'Legal Off-Road'}
          %input{name: 'currency_code', type: 'hidden', value: 'USD'}
          %button.btn.btn-info.btn-large{type: 'submit'}
            Donate

app/views/welcome/index.html.haml
#index-banner.parallax-container
  .section.no-pad-bot
    .container
      %br
      %br
      %h1.header.center.teal-text.text-lighten-2 Register Your Bike
      .row.center
        %h5.header.col.s12.light Fill out a simple form to get a street legal dirtbike or atv title.
      .row.center
        = link_to 'Get Started', title_form_path, class: 'btn-large waves-effect waves-light teal lighten-1', id: 'download-button'
      %br
      %br
  .parallax= image_tag 'background1.jpg', alt: 'Unsplashed background img 1'
.container
  .section
    .row
      .col.m4.s12
        .icon-block
          %h2.center.brown-text
            %i.material-icons mode_edit
          %h5.center Fill Out Form
          %p.light.center Fill out the form and a PDF will be generated and downloaded. Follow additional instructions to complete required paperwork.
      .col.m4.s12
        .icon-block
          %h2.center.brown-text
            %i.material-icons send
          %h5.center Send Forms
          %p.light.center Send out forms to address on pdf. You should get a call/email in a few days when your order is ready for payment.
      .col.m4.s12
        .icon-block
          %h2.center.brown-text
            %i.material-icons cake
          %h5.center Receive Title/Plates
          %p.light.center Receive plates 5-7 days after payment. Title will come 3-4 weeks after payment. You can then transfer the title to your state or just bike registered where in SD.
#index-banner.parallax-container
  .section.no-pad-bot
    .container
      %br
      %br
      .row.center
        %h1.header.col.s12.light Adventure is Out There
        %h4.header.col.s12.light “Oh the places you’ll go.” - ƒfar Seuss
  .parallax= image_tag 'background2.jpg', alt: 'Unsplashed background img 2'
.container
  .section
    .row
      .col.s16.center
        %h3
          %i.mdi-content-send.brown-text
        %h4 Why I Built This
        %p.left-align.light.center I like many of love riding. Every time you want to ride you have to load up your dirtbike, drive to a trail, park somewhere rediculouse, have your fun, then have to load it back up and do it all over again. Why not throw some legal lights on it and not have to deal with a ton of state inspections to be legal and insured. I completed this and it gave me hours of joy on my dirtbike. I hope the same to you. Please donate as your heart desires.
.teal.center.about
  .row.no-bottom-padding
    .col.offset-l1.l5.s12
      %h5.white-text About Me
      %p.grey-text.text-lighten-4 I am a developer living in Fort Collin, CO that loves to build cool tool/gadgets. I love riding, hiking, and anything outdoors. Please donate to keep this site up and to get more riders on the trails. Any amount would help support and continue development and is greatly appreciated
    .col.l6.s12.center
      %h5.white-text Donate
      %br
      %form{action: 'https://www.paypal.com/cgi-bin/webscr', method: 'post', target: '_blank'}
        %input{name: 'cmd', type: 'hidden', value: '_donations'}
        %input{name: 'business', type: 'hidden', value: 'KVHNU3QL5C2HN'}
        %input{name: 'item_name', type: 'hidden', value: 'Legal Off-Road'}
        %input{name: 'currency_code', type: 'hidden', value: 'USD'}
        %button.btn-large.waves-effect.waves-light.green.lighten-1{type: 'submit'}
          Donate